// <auto-generated />
namespace Vehicle.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class _1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709202037561_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
